config/routes.rb
Rails.application.routes.draw do
  get 'generator/index'

  get 'homepage/index'
  
  resources :generator

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/generator.rb
class Generator < ApplicationRecord
end

app/models/rand_discipline.rb
class RandDiscipline < ApplicationRecord
end

app/models/rand_order.rb
class RandOrder < ApplicationRecord
end

app/models/rand_profession.rb
class RandProfession < ApplicationRecord
end

app/models/rand_race.rb
class RandRace < ApplicationRecord
end

app/models/randrace_record.rb
class RandRace < ActiveRecord::Base
    serialize :race
end
    
    test = RandRace.new
    test.race = ["Human", "Charr", "Asura", "Sylvari", "Norn"]
    test.save
    test.race

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/generator_controller.rb
class GeneratorController < ApplicationController
  
  def show
    @overrace = params[:race]
    @overorder = params[:order]
    @overprofession = params[:profession]
    @overdiscipline = params[:discipline]
  end
  
  def index
    @generators = Generator.all
  end
  
  def new
    @generator = Generator.new
  end
  
  def create
    @generator = Generator.new(params[:generator])
    
    @generator.save
    redirect_to @generator
  end
  
  def edit
    @generator = Generator.find(params[:id])
  end
  
  def update
    @generator = Generator.find(params[:id])
    
    if @generator.update(generator_params)
      redirect_to @generator
      
    else 
      render 'edit'
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generator_helper.rb
module GeneratorHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/generator/create.html.erb
<h1>Generator Override</h1>

<p>Race: <%= @overrace %> <%= @randrace = RandRace.order("RANDOM()").limit(1).first.race %></p>
<p>Profession: <%= @randprofession = RandProfession.order("RANDOM()").limit(1).first.profession %></p>
<p>Order: <%= @randorder = RandOrder.order("RANDOM()").limit(1).first.order %></p>
<p>Discipline: <%= @randdiscipline = RandDiscipline.order("RANDOM()").limit(1).first.discipline %></p>

<div class = "button">
<%= link_to 'Generate Again', ("/generator/index") %>
</div>
<div class = "button">
<%= link_to 'Home', ("/homepage/index") %>
</div>

app/views/generator/edit.html.erb
<h1>Editing character</h1>
 
<%= form_for :generator, url: generator_path(@generator), method: :patch do |f| %>
 
  <% if @generator.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@generator.errors.count, "error") %> prohibited
        this generator from being saved:
      </h2>
      <ul>
        <% @generator.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', generators_path %>

app/views/generator/index.html.erb
<h1>Generator</h1>

<p>Race: <%= @randrace = RandRace.order("RANDOM()").limit(1).first.race %></p>
<p>Profession: <%= @randprofession = RandProfession.order("RANDOM()").limit(1).first.profession %></p>
<p>Order: <%= @randorder = RandOrder.order("RANDOM()").limit(1).first.order %></p>
<p>Discipline: <%= @randdiscipline = RandDiscipline.order("RANDOM()").limit(1).first.discipline %></p>

<div class = "button">
<%= link_to 'Generate Again', ("/generator/index") %>
</div>
<div class = "button">
<%= link_to 'Home', ("/homepage/index") %>
</div>

app/views/generator/show.html.erb
<h1>Generator Override</h1>

<p>Race: <% if @overrace == nil %>
<%= @randrace = RandRace.order("RANDOM()").limit(1).first.race %></p>
<% else %>
<%= @overrace %>
<% end %>

<p>Profession: <% if @overprofession == nil %>
<%= @randprofession = RandProfession.order("RANDOM()").limit(1).first.profession %></p>
<% else %>
<%= @overprofession %>
<% end %>

<p>Order: <% if @overorder == nil %>
<%= @randorder = RandOrder.order("RANDOM()").limit(1).first.order %></p>
<% else %>
<%= @overorder %>
<% end %>

<p>Discipline: <% if @overdiscipline == nil %>
<%= @randdiscipline = RandDiscipline.order("RANDOM()").limit(1).first.discipline %></p>
<% else %>
<%= @overdiscipline %>
<% end %>

<div class = "button">
<%= link_to 'Home', ("/homepage/index") %>
</div>

app/views/homepage/index.html.erb
<h1>Character Generator</h1>

<div class = "button">
<%= link_to 'Generate', controller: 'generator'%>
</div>


<h2>Override</h2>

<%= form_tag("/generator/show", method: "get") do %>
    <h3>Race:</h3>
    <%= radio_button_tag(:race, "Human") %>
    <%= label_tag("race_human", "Human") %><br>
    <%= radio_button_tag(:race, "Charr") %>
    <%= label_tag("race_charr", "Charr") %><br>
    <%= radio_button_tag(:race, "Norn") %>
    <%= label_tag("race_norn", "Norn") %><br>
    <%= radio_button_tag(:race, "Asura") %>
    <%= label_tag("race_asura", "Asura") %><br>
    <%= radio_button_tag(:race, "Sylvari") %>
    <%= label_tag("race_sylvari", "Sylvari") %><br><br>
    <h3>Profession:</h3>
    <%= radio_button_tag(:profession, "Warrior") %>
    <%= label_tag("profession_warrior", "Warrior") %><br>
    <%= radio_button_tag(:profession, "Guardian") %>
    <%= label_tag("profession_guardian", "Guardian") %><br>
    <%= radio_button_tag(:profession, "Revenant") %>
    <%= label_tag("profession_revenant", "Revenant") %><br>
    <%= radio_button_tag(:profession, "Thief") %>
    <%= label_tag("profession_thief", "Thief") %><br>
    <%= radio_button_tag(:profession, "Ranger") %>
    <%= label_tag("profession_ranger", "Ranger") %><br>
    <%= radio_button_tag(:profession, "Engineer") %>
    <%= label_tag("profession_engineer", "Engineer") %><br>
    <%= radio_button_tag(:profession, "Elementalist") %>
    <%= label_tag("profession_elementalist", "Elementalist") %><br>
    <%= radio_button_tag(:profession, "Necromancer") %>
    <%= label_tag("profession_necromancer", "Necromancer") %><br>
    <%= radio_button_tag(:profession, "Mesmer") %>
    <%= label_tag("profession_mesmer", "Mesmer") %><br><br>
    <h3>Order:</h3>
    <%= radio_button_tag(:order, "The Vigil") %> 
    <%= label_tag("order_vigil", "The Vigil") %><br>
    <%= radio_button_tag(:order, "The Order of Whispers") %> 
    <%= label_tag("order_whispers", "The Order of Whispers") %><br>
    <%= radio_button_tag(:order, "The Durmand Priory") %> 
    <%= label_tag("order_priory", "The Durmand Priory") %><br><br>
    <h3>Discipline:</h3>
    <%= radio_button_tag(:discipline, "Armorsmithing") %>
    <%= label_tag("discipline_armorsmithing", "Armorsmithing") %><br>
    <%= radio_button_tag(:discipline, "Artificer") %>
    <%= label_tag("discipline_artificer", "Artificer") %><br>
    <%= radio_button_tag(:discipline, "Chef") %>
    <%= label_tag("discipline_chef", "Chef") %><br>
    <%= radio_button_tag(:discipline, "Huntsman") %>
    <%= label_tag("discipline_huntsman", "Huntsman") %><br>
    <%= radio_button_tag(:discipline, "Jeweler") %>
    <%= label_tag("discipline_jeweler", "Jeweler") %><br>
    <%= radio_button_tag(:discipline, "Leatherworker") %>
    <%= label_tag("discipline_leatherworker", "Leatherworker") %><br>
    <%= radio_button_tag(:discipline, "Scribe") %>
    <%= label_tag("discipline_scribe", "Scribe") %><br>
    <%= radio_button_tag(:discipline, "Tailor") %>
    <%= label_tag("discipline_tailor", "Tailor") %><br>
    <%= radio_button_tag(:discipline, "Weaponsmith") %>
    <%= label_tag("discipline_weaponsmith", "Weaponsmith") %><br><br>
    <div class = "button"><%= submit_tag("Generate with Overrides", name: 'generator[show]') %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RPGgenerator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>